name: Deploy docs

on:
  push:
    branches: [main]

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build:finished
      - name: Build docs
        run: yarn docs:build
      - name: Create central directory
        run: mkdir -p docs
      - name: Consolidate
        run: mv packages/*/docs/* docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: docs