name: Validate Build

on: [push]

jobs:
  test:
    runs-on: node:latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run the unit tests
        run: yarn test
