name: Validate

on:
  push:
    branches-ignore: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion: ['12', '14', '16']
    name: Validate (Node ${{ matrix.nodeVersion }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: yarn
      # - name: Lint
      #   run: yarn lint
      - name: Test
        run: yarn test
  